name : build and deploy
on:
  push:
    branches:
      - main
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: use node v3
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install dependencies
      run: npm ci
    - name: build
      run: npm run build

    - name: deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.deploy_key }}
        publish_dir: out
        allow_empty_commit: true
        enable_jekyll: true
